apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-conf
data:
  default.conf: |
    server {
        listen       80;
        server_name  _;
        location / {
            root   /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }
        location /ws {
            proxy_pass http://chat-backend.default.svc.cluster.local:8080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_read_timeout 86400;
        }
    }